export const FEED_ADD_CHANNELS = 'FEED_ADD_CHANNELS';
export const FEED_REMOVE_CHANNELS = 'FEED_REMOVE_CHANNELS';
export const FEED_ADD_TRACKS = 'FEED_ADD_TRACKS';
export const FEED_SET_PROPS_CHANNEL = 'FEED_SET_PROPS_CHANNEL';
export const FEED_SET_SORT_TRACKS = 'FEED_SET_SORT_TRACKS';
export const FEED_SET_ERROR_TRACK = 'FEED_SET_ERROR_TRACK';
export const FEED_SET_CURRENT_TRACK = 'FEED_SET_CURRENT_TRACK';
export const FEED_SELECT_NEXT_TRACK = 'FEED_SELECT_NEXT_TRACK';
