export const PLAYLIST_SELECT = 'PLAYLIST_SELECT';
export const PLAYLIST_SELECT_NEXT = 'PLAYLIST_SELECT_NEXT';
export const PLAYLIST_TOGGLE_PLAYING = 'PLAYLIST_TOGGLE_PLAYING';
export const PLAYLIST_TOGGLE_LOADING = 'PLAYLIST_TOGGLE_LOADING';
export const PLAYLIST_ITEMS_ADD = 'PLAYLIST_ITEMS_ADD';
export const PLAYLIST_ITEMS_REMOVE = 'PLAYLIST_ITEMS_REMOVE';

export const CHANNELS_ADD = 'CHANNELS_ADD';
export const CHANNELS_REMOVE = 'CHANNELS_REMOVE';
export const CHANNELS_TOGGLE = 'CHANNELS_TOGGLE';
