export const TRACKS_ITEMS_ADD = 'TRACKS_ITEMS_ADD';
export const TRACKS_TOGGLE_PLAYING = 'TRACKS_TOGGLE_PLAYING';
export const TRACKS_TOGGLE_LOADING = 'TRACKS_TOGGLE_LOADING';
export const TRACKS_SELECT = 'TRACKS_SELECT';

export const CHANNELS_ADD = 'CHANNELS_ADD';
export const CHANNELS_REMOVE = 'CHANNELS_REMOVE';
export const CHANNELS_LOADING = 'CHANNELS_LOADING';
export const CHANNELS_ITEM_PROPS = 'CHANNELS_ITEM_PROPS';
